### ISSUE TITLE
Eliminate dependency on OpenMP

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1736]
We rely on OpenMP to parallelize the code. This solution has its advantages and drawbacks:

### PROs
- This is very simple to do: a single `#pragma omp` is sufficient to parallelize a loop;
- OMP implementation is well-tested and robust, with very few bugs;

### CONs
- The easiest approach is not always the best. OpenMP is not 100% efficient, especially when it comes to ordered loops;
- If a problem occurs in OpenMP code, it is very hard to debug;
- Bugs in auto-generated OpenMP code are impossible to fix, because this code is added at the compiler level (there will be bugs in our own implementation too, and probably much more, but at least we'd be able to find and fix them);
- There is a known problem where forking a process with an existing OpenMP pool will cause the child process to deadlock;
- OpenMP support requires us to distribute an openmp dynamic library, which itself is problematic, and for example prevents us from creating "many-linux" distribution on PyPI;
- If another library uses OpenMP too (eg. numpy), there may be a problem with using these libraries together;
- OpenMP provides a number of useful parallel constructs out of the box, but they cannot be extended easily.

## Roadmap

- [x] Use atomics instead of OpenMP in `shared_bmutex`;
- [x] **Implement basic thread pool**;
- [x] Implement parallel for loop with static scheduling (see "parallel.cc");
- [x] Implement parallel for loop with dynamic scheduling (#1772);
- [x] Implement parallel for ordered loop using a thread pool (#1775);
- [x] Implement atomic float and double (with arithmetics);
- [x] Implement atomic min and max functions (#1763);
- [x] Implement parallel_for_static nested inside parallel_region (#1762);
- [x] Implement parallel_for_dynamic nested inside parallel_region (#1776);
- [x] Avoid critical section in `TRACK()` and `UNTRACK()`;
- [x] Avoid `#pragma omp` in column_fw.cc;
- [x] Avoid `#pragma omp` in column_string.cc;
- [x] Eliminate `#pragma omp` in rowindex_array.cc;
- [x] Get rid of `#pragma omp` in sort.cc;
- [x] Remove `#pragma omp`s in stats.cc;
- [x] Use new thread pool in csv writer;
- [x] Get rid of `#pragma omp` in expr/reduce.cc;
- [x] Stop using `#pragma omp` in expr/string_expr.cc;
- [x] Avoid `#pragma omp` in frame/join.cc;
- [x] Expel `#pragma omp` from to_numpy.cc;
- [x] Purge all uses of `#pragma omp` in aggregator.cc;
- [x] Get rid of omp-critical and atomic sections in ftrl algo;
- [x] Stop using omp in split_into_nhot.cc;
- [x] Replace omp ordered loop in fread with an implementation using the new thread pool;
- [x] Ensure thread pool behaves correctly during fork;
- [x] Remove omp library itself (including any compilation flags, dll bundling, etc).

**Comment by tomkraljevic** [comment]
@tomkraljevic - ccing myself...
