### ISSUE TITLE
Use PEP-517/518-compliant build process

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#2258]
[PEP-518](https://www.python.org/dev/peps/pep-0518/) introduces new format for distributing python packages: based on `pyproject.toml` configuration file. In addition, [PEP-517](https://www.python.org/dev/peps/pep-0517/) describes the API for a "build backend" capable of creating source distributions and binary wheels.

This epic therefore consists of:
- [x] Create a new system (`xbuild`) for building the binary extensions (#2235, #2246);
- [x] Implement wheel-building functionality (#2247);
- [x] Implement creating source distributions in xbuild (#2257);
- [x] Use auditwheel to verify wheel integrity on Linux distribution (#2266);
- [x] Deploy `xbuild` as the primary tool for CI pipelines (#2276);
- [x] Generate version string and version files in ext.py (#2287);
- [x] Remove old code used for building datatable.

**Comment by st-pasha** [comment]
So it appears we need `pip >= 20.0` for this, which will be released in Jan 2020. 
For now, you'd need to do `pip install git+https://github.com/pypa/pip` to get the bleeding edge version of `pip`.
