### ISSUE TITLE
Roadmap for v0.11.0

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#2281]
This is the list of things we'd want to have implemented for the next major release of datatable. The list is subject to change, but hopefully it will see more additions than deletions:

- [ ] Full support of datasets with >2B rows (#2336)
- [ ] Inner/outer joins (#1080)
- [ ] Date/time columns (#1646)
- [ ] User-defined aggregator / map functions (#1960)
- [x] Windows builds (#1114, ~~#1369~~)
- [x] Revamp build process: use PEP-517 compliant build pipeline (~~#2258~~)
- [x] Improve documentation:
    - [x] Better changelogs (#2304)
    - [x] Better API documentation
    - [x] More tutorials / overviews / specific topic descriptions
- [ ] Fread improvements:
    - [ ] Implement streaming reading (#1958, ~#1843~, ~#1750~)
    - [ ] Implement reading + filtering (#1950)
    - [x] Better support for multi-file reading (~#2008~, ~#2392~)
    - [ ] Better auto-detection of parse settings (~~#1343~~, #1045, #1036, #946, #934, #922, #518)
- [ ] Functions for string manipulations
    - [x] Convert strings into integers/booleans/floats (#1313)
    - [ ] Apply slice to a string (#1667)
    - [ ] Convert to upper/lower case
    - [x] Append strings (`+`)
    - [ ] Repeat strings (`*`)
    - [ ] Strip whitespace / other characters
- [ ] Functions for date/time manipulations
- [x] Remove dependencies on external libraries:
    - [x] typesentry (#1535)
    - [x] blessed (#1677)
- [ ] Rolling windows support (#1500)

**Comment by oleksiyskononenko** [comment]
@arnocandel could you please add some details here on the new model we want to add to datatable?
