### ISSUE TITLE
Changelog improvements

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#2304]
This meta-issue describes the overall effort to improve the Changelog feature in datatable:

- [x] Implement Sphinx extension for changelogs (#2275);
- [x] Automatically create references from each changelog to previous/next versions (#2307);
- [x] Add ability to list wheel files in the infobox (#2316);
- [x] Convert changelog of version 0.11.0 to use the new format (#2275);
- [x] Convert changelog of version 0.10.1 to use the new format (#2278);
- [x] Convert changelog of version 0.10.0 to use the new format (#2275);
- [x] Convert changelog for version 0.9.0 to `.rst` format (#2278);
- [x] Convert changelog for version 0.8.0 to `.rst` format (#2279);
- [x] Convert changelog for version 0.7.0 to `.rst` format (#2310);
- [x] Convert changelog for version 0.6.0 to `.rst` format (#2311);
- [x] Convert changelog for version 0.5.0 to `.rst` format (#2311);
- [x] Convert changelog for version 0.4.0 to `.rst` format (#2311);
- [x] Convert changelog for version 0.3.2 to `.rst` format (#2313);
- [x] Convert changelog for version 0.3.1 to `.rst` format (#2313);
- [x] Convert changelog for version 0.3.0 to `.rst` format (#2314);
- [x] Convert changelog for version 0.2.2 to `.rst` format (#2315);
- [x] Convert changelog for version 0.2.1 to `.rst` format (#2315);
- [x] Rename changelog -> "Release History" where practical (#2310);
- [x] Remove old CHANGELOG.md file (#2315);
- [x] Create directive `xcontributors` for listing changelog authors;
- [x] Create special page that lists all contributors automatically gathered from all `xcontributors` directives (#2330);
- [x] Remove old AUTHORS.md file (#2330);
