### ISSUE TITLE
Documentation checklist

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#2604]
The aim here is to have a checklist of documentation suggestions, and also to keep track, in case others have suggestions or are already working on one, they can reference from here : 

- [ ]  pandas vs datatable syntax comparison, showing how to replicate common pandas operations

- [ ]  rdatatable vs datatable syntax comparison, for users wishing to replicate familiar operations in R

- [ ]  sql vs datatable comparison, for sql users transiting to datatable

- [ ]  add examples to functions in docstrings; this will help users understand how to use the functions quickly, 

- [ ]  transformation documentation

- [ ]  documentation on joins

- [ ]  documentation on conditional operations

- [ ]  string operations in datatable

- [ ] cookbook

- [ ] updates to existing documentation (e.g fread ... more information on fread and excel (named ranges, ...)

Contributions/suggestions on what should be included as documentation are welcome

**Comment by st-pasha** [comment]
Hi Samuel,
thanks for taking up this initiative. As you probably noticed, we've spent a significant effort lately to improve our documentation. We're currently mostly focused on documenting the API, but various tutorials / user guides might be just as useful if not more useful.
I've sent you an invite to join the project, so that you can create PRs directly (without going through the trouble of forking), and also better manage issues: assign labels, projects, milestones, etc.

**Comment by samukweku** [comment]
Yes, I noticed documentation on the API. I was particularly happy to see the guide on creating and adding a function to datatable. Thanks for the opportunity @st-pasha

**Comment by myamullaciencia** [comment]
Great Initiative @samukweku, I would choose one or two sections from the checklist and get back to yours here sooner. and i will let yours know if i need any help.

**Comment by samukweku** [comment]
@myamullaciencia cool! Will be on the lookout for your PR

**Comment by st-pasha** [comment]
Samuel, have you seen #2400 -- do you think it's something that can be incorporated inside your data.table/datatable comparison page?

**Comment by samukweku** [comment]
@st-pasha It is a good idea. I will make a PR to cover that.

**Comment by samukweku** [comment]
@st-pasha I noticed that datatable docs does not get updated when new docs are added. Same goes for the changelog. Any reasons for this? Maybe a design decision? I believe users (me included) would love to get access to new information.

**Comment by st-pasha** [comment]
I've set up a webhook just now, so hopefully it'll start building automatically now.

**Comment by samukweku** [comment]
@st-pasha No worries; I'll keep checking the site. At the moment, it has not updated.

**Comment by samukweku** [comment]
Website updates fine now

**Comment by samukweku** [comment]
- update transform documentation on `extend` - it covers more than just a dictionary. 
- Add example to select documentation on columns with `alias` for renaming
