### ISSUE TITLE
[COMMENT] Roadmap comments from DAI perspective

### ISSUE THREAD

**Issue by mmalohlava** [h2oai/datatable#2700]
This is the list of issues annotated by the priority from DAI perspective:

## Top Priority 
Goal: optimize computation speed, minimize data conversions

- [ ] Optimize MLI code to adopt datatable (DAI: <kbd>TOP</kbd>, time needed: ?)
- [ ] Arrow support/conversion (TODO issue) (DAI: <kbd>TOP</kbd>, time needed: ?)
- [ ] Tighter integration with LGBM (maybe the arrow support is the way): (DAI: <kbd>TOP</kbd>, time needed: ?)
   - Note: LGBM can accept native datatable frame for computation (no conversion to pandas/numpy)
   - Note: This will need change in LGBM

## High Priority
- [ ] Date/time columns (#1646) (DAI: <kbd>HIGH</kbd>, time needed: ?)
- [ ] Interpretable model (TODO issue) (DAI: <kbd>HIGH</kbd>, time needed: ?)
- [ ] Performance on multi-core systems/cache trashing (TODO issue) (DAI: <kbd>HIGH</kbd>, time needed: ?)

## Other
- [ ] Full support of datasets with >2B rows (#2336) (DAI: <kbd>MEDIUM</kbd>, time needed: ?) 
    - Note: ability to read and write is good enough as the first step
    - Note: efficient version needs lot of effort
- [ ] Inner/outer joins (#1080) (DAI: <kbd>LOW</kbd>)
- [ ] Ability to score MOJO in efficient way (`f.score(mojo)`) (DAI: <kbd>MEDIUM</kbd>, time needed: ?)
- [ ] Fread improvements:
    - [ ] Implement streaming reading (#1958, ~#1843~, ~#1750~) (DAI: <kbd>LOW</kbd>, time needed: ?)
    - [ ] Implement reading + filtering (#1950) (DAI: <kbd>LOW</kbd>, time needed: ?)
    - [ ] Better auto-detection of parse settings (~~#1343~~, #1045, #1036, #946, #934, #922, #518) (DAI: <kbd>LOW</kbd>, time needed: ?)
- [ ] User-defined aggregator / map functions (#1960) (DAI: <kbd>LOW</kbd>, time needed: ?)

- [ ] Functions for string manipulations (DAI: <kbd>MEDIUM</kbd>, time needed: ?)
    - [ ] Apply slice to a string (#1667)
    - [ ] Convert to upper/lower case
    - [ ] Repeat strings (`*`)
    - [ ] Strip whitespace / other characters
- [ ] Functions for date/time manipulations (DAI: <kbd>LOW</kbd>, time needed: ?)
- [ ] Rolling windows support (#1500) (DAI: <kbd>LOW</kbd>, time needed: ?)

## New proposals
- [ ] Data compression (DAI: <kbd>MEDIUM</kbd>, time needed: ?)
- [ ] Data encryption in Jay file (DAI: <kbd>MEDIUM</kbd>, time needed: ?)
- [ ] Per column Jay file, support for efficient sporadic data updates (DAI: <kbd>LOW</kbd>, time needed: ?)
- [ ] Distributed mode of datatable (via Dask) (DAI: <kbd>LOW</kbd>, time needed: ?)

**Comment by mmalohlava** [comment]
Any news on time-estimates?
