### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#290]
- [x] Rollup stats for each column (#276)
- [x] Write a CSV file
- [x] Generalized computational graph (#1477)
- [x] Grouping by a single column (integer type)
- [x] Group-by reduction operators: sum, min, max, mean, etc.
- [x] Grouping by a single column (other types)
- [x] Modify data in a datatable in-place
- [x] Sorting by multiple columns
- [x] Grouping by multiple columns
- [ ] Joining (inner, left outer)
- [x] Insert / delete rows
- [x] Computation on variable-width columns (strings)
- [ ] String operations
- [ ] Rolling join
- [ ] Group-by operators that involve sorting: median, quantile, rank (median also in https://github.com/h2oai/datatable/issues/1530)
- [x] rbind disk-based columns
- [x] Keys to optimize performance
- [ ] Non-equi joins
- [ ] Compute rollup stats during fread
- [ ] Categorical (enum) type
- [ ] Datetime type
- [ ] Time window functions
- [ ] Full join
- [ ] fread auto-detected parse format save into FReader object
- [ ] skipna parameter for reduction operators
- [ ] Repro of NYCTaxi analytics using datatable
- [ ] Benchmark Szilard's test (grouping vs joining)
- [ ] Benchmark against fst & paratext
- [x] Benchmark parity with R data.table 5 grouping tests - https://h2oai.github.io/db-benchmark/
- [ ] Benchmark against TPC-H
- [ ] Finish fread outstanding bug master list ([#2247](https://github.com/Rdatatable/data.table/issues/2247))
- [ ] Comparison of fread capabilities against other read csv frameworks (esp. smart capabilities)
- [ ] Demo of interoperability with other frameworks
- [ ] Log operations with datatable (data provenance)
- [ ] Read/write into feather (#1461)

**Out of scope**
- Multi-user access, including permissions
- Sharded data files, growing file size

**Comment by jangorecki** [comment]
Marked _Benchmark parity with R data.table 5 grouping tests_ as resolved.
What about `cor`, `cov`, `var` functions, are they going to be in scope? Asking because `cor` or `cov+var` is required to answer q9 in groupby benchmark.

**Comment by st-pasha** [comment]
@jangorecki  Of course, `cor`, `cov`, `var` are all quite straightforward, no reason not to add them.

**Comment by st-pasha** [comment]
Replaced with #2281

**Comment by mdancho84** [comment]
Hi @st-pasha awesome work! I was wondering what the schedule is for some of the ["Missing Functionality"](https://datatable.readthedocs.io/en/latest/manual/comparison_with_pandas.html#missing-functionality). I'm particularly interested in the pivoting and wide to long functions, which are the most apparent gaps between Pandas and datatable. Anyways, nice work on the package. It's very fast. Yay!

**Comment by st-pasha** [comment]
@mdancho84 Our current immediate focus is date-time functionality. After that we can get to pivoting/melting. See also this discussion: https://github.com/h2oai/datatable/discussions/2677

**Comment by mdancho84** [comment]
@st-pasha Thanks a lot for your response. Much appreciated. Date/time is super important.
