### ISSUE TITLE
Implement pandas.describe sufficiently minimal for DAI stats

### ISSUE THREAD

**Issue by nkalonia1** [h2oai/datatable#335]
A Frame object should be able to provide:

- [x] The number of unique values in a column (~~#856~~, ~~#858~~)
- [x] The most frequent item in a column (the mode) (~~#860~~, ~~#863~~)
- [x] The number of occurrences of the most frequent item (~~#860~~)

NAs are not included. If more than one item shares the spot for most frequent item, then either one can be returned.
As with the other statistics, all results should be returned in a Frame.

```
>>> d = dt.DataTable([1, 2, 3, 3, 2, 3, 1, 3, 2, None])

>>> d.nunique().topython()
[[4]]
>>> d.mode().topython()
[[3]]
>>> d.modefreq().topython()
[[4]]
```
Function names are subject to change.
