### ISSUE TITLE
Implement all parameters supported by fread in R

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#35]
- [x] `input` / `file`: file name to read, or input as a string
- [x] `sep`: field separator
- [x] `nrows`: maximum number of rows to read
- [x] `header`: does the first data line contain column names
- [x] `na.strings`: list of strings to be interpreted as NA values #95
- <del>`stringsAsFactors`: convert all strings to categoricals</del> -- cannot support until we have categorical type
- [x] `verbose`: debugging output
- [x] `skip`: how many rows to skip, or skip to row containing this string #86
- [x] `select` / `drop`: Keep some and drop other columns in the file #83
- [x] `colClasses`: override column types #83
- [x] `dec`: decimal separator (for numbers)
- [x] `col.names`: override column names #83
- <del>`check.names`: check column names are valid and have no duplicates</del> -- always on
- [x] `encoding`
- [x] `quote`: dubious, need to rethink. Perhaps this should be `quoteRule` instead?
- [x] `strip.white`: strip leading/trailing whitespace from unquoted fields
- [x] `fill`: allow ragged columns
- [x] `blank.lines.skip`: ignore blank lines
- [x] `showProgress`: display progress bar
- [x] `nThread`: number of threads to use.
