### ISSUE TITLE
Requirements for H₂Oªⁱ MLI

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#37]
- [x] Appends/rbind (<del>#41</del>, <del>#45</del>, <del>#63</del>, <del>#65</del>, <del>#66</del>, <del>#108</del>, <del>#109</del>, <del>#116</del>, <del>#121</del>, <del>#123</del>)
- [x] Merge/cbind (<del>#132</del>)
- [x] Calculation of mean, median, mode by column (<del>#276</del>)
- [x] Imputation with mean, median, mode
- [x] Column-and-row-based updates, including setting to missing
- [x] Column-based updates, including setting to missing
- [x] Row-based updates, including setting to missing
- [x] Column drop (<del>#38</del>)
- [x] Column rename (<del>#52</del>)
- [x] Creating new frames and adding rows and columns to new frames
- [x] Row and column subsetting (<del>#21</del>)
- [x] Sorts (https://github.com/h2oai/datatable/projects/2)
- [x] Inner and left Joins
