### ISSUE TITLE
Requirements for AutoDL

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#62]
**General**
- [x] Read file from CSV (via fread)
- [x] Drop columns (in-place)
- [x] Extract a single column from the datatable
- [x] Convert datatable to a pandas dataframe (~~#59~~, ~~#67~~, ~~#150~~)
- [x] Convert pandas dataframe to datatable (~~#69~~, ~~#146~~, ~~#178~~)
- [x] Convert numeric datatable to numpy array (~~#177~~)
- [ ] Drop duplicate rows (~~#694~~)
- [x] Count unique values in a column
- [x] Convert column to numeric (i.e ability to convert any column to float32 / float64 somehow) (~~#719~~, ~~#415~~)
- [x] Make `numpy.array(dt)` work if `dt` has a single-column (~~#177~~, ~~#182~~, ~~#183~~)
- [x] Select a subsection of datatable by an explicit index (which could be a numpy array) (~~#186~~)
- [x] Sorting (~~#194~~, ~~#197~~, ~~#198~~, ~~#199~~, ~~#200~~, ~~#201~~, ~~#202~~, ~~#205~~, ~~#211~~, ~~#217~~)
- [x] Grouping 
- [x] Aggregations (mean, min, max) (~~#715~~, ~~#716~~)
- [x] Joining

**Support for categorical columns**
- [ ] Convert column to categorical (in-place)
- [ ] Replace categories list for a categorical column
- [ ] Replace a single category within the categories list

**Support for datetime columns**
- [ ] Convert string/categorical columns to date columns

**Comment by st-pasha** [comment]
Too old
