### ISSUE TITLE
Add ability to evaluate column expressions without LLVM

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#697]
This will ensure better operation for users who don't have LLVM on their systems; can be utilized for small dataset where code construction / compilation step adds significant overhead compared to the actual data processing time; may be used for simple "predefined" transforms; may be used as fallback if something goes wrong with LLVM mechanism; will provide a way to better check the validity of results during testing.

Due to complexity of this task, it will be split into multiple smaller sub-issues:
- [x] Implement ability to construct a DataTable from a list of `_datatable.Column` objects.
- [x] Add parameter `engine` to the `DataTable.__call__()`, allowing the user to choose explicitly which execution engine to use (default to "llvm" however).
- [x] Implement eager evaluation for `ColumnSelector` nodes.
- [x] Implement eager evaluation for `BinaryOp` node for main arithmetic operations and without allowing either side to be a scalar.
- [x] Add support for eager evaluation of `RowFilter` nodes.
- [x] Add support for eager evaluation of `Sort` nodes.
- [x] Implement eager evaluation for `LiteralExpr` node, which should wrap the value into a 1-row Column.
- [x] Implement eager evaluation for `BinaryOp` nodes when one of the operands is a scalar.
- [x] Implement eager evaluation for `IsNa` node.
- [x] Implement eager evaluation for `RelationalOp` node.
- [x] Implement eager evaluation for `UnaryOp` node.
- [x] Implement eager evaluation for `Mean` reducer node.
- [x] Implement eager evaluation for `Min` and `Max` reducer nodes.
- [x] Implement eager evaluation for `Stdev` reducer node.
- [x] Modify the evaluation graph so that "eager" engine performs only eager evaluations.
- [x] Automatically choose "eager" evaluator if LLVM runtime is not available (~~#725~~).
