### ISSUE TITLE
Use eager evaluation engine by default

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#841]
It's easier to develop new features with eager engine, so we should use that for now. We can implement and release group-by functionality and certain core transformations with eager engine faster, then the llvm implementation can be added later.

Switching to "eager" by default is easy, however we need to ensure that all existing tests work well in that mode. Prerequisites:
- [x] Rows filter isn't applied correctly to view frame under eager engine (#726)
- [x] Inverse operator converts `bool8` column into `int8` (#840)
- [x] Eager evaluation fails with mixed computed / referenced columns (#843)
